services:
  profiling_bot:
    build: .
    container_name: profiling_bot
    env_file: .env
    command: ./scripts/entrypoint-bot.sh
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:8001:8000
